name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
<<<<<<< HEAD
    - run: sh setEnvironment.sh ${{ secrets.FIREBASE_API_KEY }
=======
    - run: sh setEnvironment.sh ${{ secrets.FIREBASE_API_KEY }}
>>>>>>> 54ed60d9123b75301afcab801aa8dfd0877ac173
    - uses: actions/setup-node@master
      with:
        node-version: '10.13'
    - run: npm install
    - run: npm run build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting --project weblaunch-web
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
